services:
  - type: web
    name: supertokens
    env: docker
    repo: https://github.com/hmbrg/supertokens-on-render.git
    plan: starter
    envVars:
      # - key: POSTGRESQL_CONNECTION_URI
      #   fromDatabase:
      #     name: supertokens-db
      #     property: connectionString
      - key: POSTGRESQL_USER
        fromDatabase:
          name: supertokens-db
          property: user
      - key: POSTGRESQL_PASSWORD
        fromDatabase:
          name: supertokens-db
          property: password
      - key: POSTGRESQL_DATABASE_NAME
        fromDatabase:
          name: supertokens-db
          property: database
      - key: POSTGRESQL_HOST
        fromDatabase:
          name: supertokens-db
          property: host
      - key: POSTGRESQL_PORT
        fromDatabase:
          name: supertokens-db
          property: port

databases:
  - name: supertokens-db
    plan: starter
    region: frankfurt
